"""empty message

Revision ID: 403867b0c827
Revises: 01f18cdc56ec
Create Date: 2022-12-12 14:22:51.240978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403867b0c827'
down_revision = '01f18cdc56ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.add_column('reservas', sa.Column('id_guia', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservas', 'users', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.drop_column('reservas', 'id_guia')
    op.drop_column('reservas', 'id_usuario')
    # ### end Alembic commands ###
