"""empty message

Revision ID: 4f8cd2b03b68
Revises: 702931b23ddc
Create Date: 2022-12-09 16:24:06.461920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8cd2b03b68'
down_revision = '702931b23ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.String(length=120), nullable=False),
    sa.Column('id_guia', sa.Integer(), nullable=False),
    sa.Column('ids_usuarios', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('nacionalidad', sa.String(length=120), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('foto2', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['id_guia'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades')
    # ### end Alembic commands ###
