"""empty message

Revision ID: 6e5a383ddfbb
Revises: 454921ad27af
Create Date: 2022-12-15 21:32:51.926467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5a383ddfbb'
down_revision = '454921ad27af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_constraint('reservas_fecha_realizacion_key', type_='unique')
        batch_op.drop_constraint('reservas_fecha_reserva_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_unique_constraint('reservas_fecha_reserva_key', ['fecha_reserva'])
        batch_op.create_unique_constraint('reservas_fecha_realizacion_key', ['fecha_realizacion'])

    # ### end Alembic commands ###
