"""empty message

Revision ID: 743763af2ce0
Revises: 94119bd2291d
Create Date: 2022-12-12 21:04:23.996744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743763af2ce0'
down_revision = '94119bd2291d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actividades_id_guia_fkey', 'actividades', type_='foreignkey')
    op.drop_constraint('comentarios_id_actividad_fkey', 'comentarios', type_='foreignkey')
    op.drop_constraint('comentarios_id_usuario_fkey', 'comentarios', type_='foreignkey')
    op.drop_constraint('reservas_id_usuario_fkey', 'reservas', type_='foreignkey')
    op.drop_constraint('reservas_id_actividad_fkey', 'reservas', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reservas_id_actividad_fkey', 'reservas', 'actividades', ['id_actividad'], ['id'])
    op.create_foreign_key('reservas_id_usuario_fkey', 'reservas', 'users', ['id_usuario'], ['id'])
    op.create_foreign_key('comentarios_id_usuario_fkey', 'comentarios', 'users', ['id_usuario'], ['id'])
    op.create_foreign_key('comentarios_id_actividad_fkey', 'comentarios', 'actividades', ['id_actividad'], ['id'])
    op.create_foreign_key('actividades_id_guia_fkey', 'actividades', 'users', ['id_guia'], ['id'])
    # ### end Alembic commands ###
