"""empty message

Revision ID: 8f60cd957a10
Revises: 743763af2ce0
Create Date: 2022-12-12 21:05:24.860923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f60cd957a10'
down_revision = '743763af2ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'actividades', 'users', ['id_guia'], ['id'])
    op.create_foreign_key(None, 'comentarios', 'actividades', ['id_actividad'], ['id'])
    op.create_foreign_key(None, 'comentarios', 'users', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'reservas', 'users', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'reservas', 'actividades', ['id_actividad'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_constraint(None, 'actividades', type_='foreignkey')
    # ### end Alembic commands ###
