"""empty message

Revision ID: 9e0c7da3704b
Revises: e10f58c47db0
Create Date: 2022-12-12 10:33:10.149030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e0c7da3704b'
down_revision = 'e10f58c47db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('texto')
    )
    op.add_column('actividades', sa.Column('fecha', sa.DateTime(), nullable=False))
    op.drop_constraint('actividades_fecha_fin_key', 'actividades', type_='unique')
    op.drop_constraint('actividades_fecha_inicio_key', 'actividades', type_='unique')
    op.create_unique_constraint(None, 'actividades', ['fecha'])
    op.drop_column('actividades', 'fecha_fin')
    op.drop_column('actividades', 'nacionalidad')
    op.drop_column('actividades', 'fecha_inicio')
    op.drop_column('actividades', 'foto2')
    op.add_column('reservas', sa.Column('fecha_realizacion', sa.DateTime(), nullable=False))
    op.drop_constraint('reservas_fecha_fin_key', 'reservas', type_='unique')
    op.drop_constraint('reservas_fecha_inicio_key', 'reservas', type_='unique')
    op.create_unique_constraint(None, 'reservas', ['fecha_realizacion'])
    op.drop_column('reservas', 'fecha_fin')
    op.drop_column('reservas', 'fecha_inicio')
    op.add_column('users', sa.Column('descripcion', sa.Text(), nullable=True))
    op.drop_column('users', 'nacionalidad')
    op.drop_column('users', 'calificacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calificacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nacionalidad', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('users', 'descripcion')
    op.add_column('reservas', sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('reservas', sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservas', type_='unique')
    op.create_unique_constraint('reservas_fecha_inicio_key', 'reservas', ['fecha_inicio'])
    op.create_unique_constraint('reservas_fecha_fin_key', 'reservas', ['fecha_fin'])
    op.drop_column('reservas', 'fecha_realizacion')
    op.add_column('actividades', sa.Column('foto2', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('actividades', sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('actividades', sa.Column('nacionalidad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('actividades', sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'actividades', type_='unique')
    op.create_unique_constraint('actividades_fecha_inicio_key', 'actividades', ['fecha_inicio'])
    op.create_unique_constraint('actividades_fecha_fin_key', 'actividades', ['fecha_fin'])
    op.drop_column('actividades', 'fecha')
    op.drop_table('comentarios')
    # ### end Alembic commands ###
