"""empty message

Revision ID: a92e74205551
Revises: ad43a5ee4ffe
Create Date: 2022-12-15 18:37:45.078019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92e74205551'
down_revision = 'ad43a5ee4ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_constraint('actividades_fecha_key', type_='unique')
        batch_op.drop_constraint('actividades_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_unique_constraint('actividades_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('actividades_fecha_key', ['fecha'])

    # ### end Alembic commands ###
