"""empty message

Revision ID: e10f58c47db0
Revises: 4f8cd2b03b68
Create Date: 2022-12-09 17:00:41.343830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10f58c47db0'
down_revision = '4f8cd2b03b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_reserva', sa.String(length=120), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha_fin'),
    sa.UniqueConstraint('fecha_inicio'),
    sa.UniqueConstraint('fecha_reserva'),
    sa.UniqueConstraint('num_reserva')
    )
    op.add_column('actividades', sa.Column('fecha_inicio', sa.DateTime(), nullable=False))
    op.add_column('actividades', sa.Column('fecha_fin', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'actividades', ['fecha_fin'])
    op.create_unique_constraint(None, 'actividades', ['fecha_inicio'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actividades', type_='unique')
    op.drop_constraint(None, 'actividades', type_='unique')
    op.drop_column('actividades', 'fecha_fin')
    op.drop_column('actividades', 'fecha_inicio')
    op.drop_table('reservas')
    # ### end Alembic commands ###
